---
abstract: "Automatically memoize your Moose objects for reuse\r"
author:
  - 'Steven Lee <stevenl@cpan.org>'
build_requires:
  File::Basename: 0
  File::Spec::Functions: 0
  Module::Build: 0.3601
  Moose: 0
  Test::Fatal: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Role-Flyweight
recommends:
  JSON::XS: 0
requires:
  JSON: 2.00
  Moose::Role: 0
  MooseX::ClassAttribute: 0.23
  Scalar::Util: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MooseX-Role-Flyweight
  repository: http://github.com/stevenl/MooseX-Role-Flyweight.git
version: 0.005
x_authority: cpan:STEVENL
