---
abstract: "Automatically memoize your Moose objects for reuse\r"
author:
  - 'Steven Lee <stevenwh.lee@gmail.com>'
build_requires:
  Moose: 0
  Test::Fatal: 0
  Test::More: 0
  lib: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300036, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Role-Flyweight
provides:
  MooseX::Role::Flyweight:
    file: lib/MooseX/Role/Flyweight.pm
    version: 1.00
recommends:
  JSON::XS: 0
requires:
  JSON: 2.00
  Moose::Role: 0
  MooseX::ClassAttribute: 0.23
  Scalar::Util: 0
  namespace::autoclean: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MooseX-Role-Flyweight
  repository: http://github.com/stevenl/MooseX-Role-Flyweight.git
version: 1.00
